# Generated by Django 4.1 on 2022-11-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_book_date_of_issue_book_publication_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book", name="date_of_issue", field=models.DateTimeField(),
        ),
    ]
