# Generated by Django 4.1 on 2022-11-19 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_alter_book_date_of_issue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="date_of_issue",
            field=models.DateTimeField(default=datetime.date(2022, 11, 19)),
        ),
    ]
